#!/bin/sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Get vsftpd version.
#======================================================================================================================

cd /tmp

VERSION=$(cat VSFTPD_BUILD)
bf-echo "vsftpd version ${VERSION}."


#======================================================================================================================
# Install vsftpd and dependencies.
#======================================================================================================================

bf-echo "Installing vsftpd v${VERSION}..."
apk add --no-cache \
    lftp \
    openssl \
    vsftpd=${VERSION}
bf-done


#======================================================================================================================
# Cleanup.
#======================================================================================================================

bf-echo "Cleaning up default vsftpd and SSL files."
rm -rf /etc/vsftpd/* /etc/ssl/private

bf-echo "Removing .empty files..."
rm /files/.empty
rm /ssl/.empty

bf-echo "Linking SSL directories."
ln -s /ssl /etc/ssl/private

bf-done
