#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Setup variables.
#======================================================================================================================

[[ -z "${FTPS_USER-}" ]] && bf-error "FTPS_USER is required."
[[ -z "${FTPS_PASS-}" ]] && bf-error "FTPS_PASS is required."

UID=${FTPS_UID:-1000}


#======================================================================================================================
# Check whether or not the FTP user already exists.
#======================================================================================================================

bf-debug "Checking user ${FTPS_USER}..."
USER_EXISTS=`getent passwd ${FTPS_USER} || echo ''`
if [ -n "${USER_EXISTS}" ] ; then
    bf-echo "User ${FTPS_USER} already exists."
    exit 0
fi


#======================================================================================================================
# Create FTP user.
#======================================================================================================================

bf-echo "Creating user ${FTPS_USER}..."
echo -e "${FTPS_PASS}\n${FTPS_PASS}" | adduser -h ${FTPS_FILES} -s /sbin/nologin -u ${UID} ${FTPS_USER}
bf-done

bf-echo "Ensuring user owns ${HOME}..."
chown ${FTPS_USER}:${FTPS_USER} ${FTPS_FILES}
bf-done
