#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Setup variables.
#======================================================================================================================

[[ -z "${FTPS_USER-}" ]] && bf-error "FTPS_USER is required."
[[ -z "${FTPS_PASS-}" ]] && bf-error "FTPS_PASS is required."

USER=${FTPS_USER}
PASS=${FTPS_PASS}
UID=${FTPS_UID:-1000}
HOME=${FTPS_FILES}


#======================================================================================================================
# Check whether or not the FTP user already exists.
#======================================================================================================================

getent passwd ${USER}  > /dev/null

if [ $? -eq 0 ]; then
    bf-echo "User ${USER} already exists."
    exit 0
fi


#======================================================================================================================
# Create FTP user.
#======================================================================================================================

bf-echo "Creating user ${USER}..."
echo -e "${PASS}\n${PASS}" | adduser -h ${HOME} -s /sbin/nologin -u ${UID} ${USER}
bf-done

bf-echo "Ensuring user owns ${HOME}..."
chown ${USER}:${USER} ${HOME}
bf-done
