#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bcg-env "VSFTPD_CONF" "/etc/vsftpd/vsftpd.conf"
bcg-env "VSFTPD_LOG" "/var/log/vsftpd.log"
bcg-env "VSFTPD_SSL_CERT" "/ssl/vsftpd.pem"
