#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Create FTP user
#======================================================================================================================

[[ -z "${FTP_USER-}" ]] && _error "FTP_USER is required."
[[ -z "${FTP_PASS-}" ]] && _error "FTP_PASS is required."

USER=${FTP_USER}
PASS=${FTP_PASS}
UID=${FTP_UID:-1000}

_echo "Creating user ${USER}..."
echo -e "${PASS}\n${PASS}" | adduser -h /sites -s /sbin/nologin -u ${UID} ${USER}
_done

FILES=/files
_echo "Giving user permission to access ${FILES}..."
chown ${USER}:${USER} ${FILES}
_done
