#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Create FTP user.
#======================================================================================================================

[[ -z "${FTPS_USER-}" ]] && bcg-error "FTPS_USER is required."
[[ -z "${FTPS_PASS-}" ]] && bcg-error "FTPS_PASS is required."

USER=${FTPS_USER}
PASS=${FTPS_PASS}
UID=${FTPS_UID:-1000}
HOME=${FTPS_FILES}

bcg-echo "Creating user ${USER}..."
echo -e "${PASS}\n${PASS}" | adduser -h ${HOME} -s /sbin/nologin -u ${UID} ${USER}
bcg-done

bcg-echo "Ensuring user owns ${HOME}..."
chown ${USER}:${USER} ${HOME}
bcg-done
