#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Create FTP configuration
#======================================================================================================================

_echo "Creating SSL certificate and key..."
mkdir -p /etc/ssl/private
openssl req -newkey rsa:1024 \
    -x509 \
    -sha256 \
    -days 3650 \
    -nodes \
    -out /etc/ssl/private/vsftpd.pem \
    -keyout /etc/ssl/private/vsftpd.pem \
    -subj "/C=NA/ST=NA/L=NA/O=NA/OU=NA/CN=vsftpd"
