#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Create FTP configuration
#======================================================================================================================

_echo "Creating SSL certificates..."
mkdir -p /etc/ssl/private
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem
