#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Create FTP configuration
#======================================================================================================================

_echo "Writing VSFTPD config..."
esh -o /etc/vsftpd/vsftpd.conf \
    /etc/templates/vsftpd.conf.esh
_done
