#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E=`basename ${0}`


#======================================================================================================================
# Create FTP configuration.
#======================================================================================================================

if [ -f ${VSFTPD_SSL_CERT} ] ; then
    bcg-echo "Using existing SSL certificate."
    exit 0
fi

bcg-echo "Creating SSL certificate and key..."
openssl req -newkey rsa:${SSL_BITS} \
    -x509 \
    -sha256 \
    -days 3650 \
    -nodes \
    -out ${VSFTPD_SSL_CERT} \
    -keyout ${VSFTPD_SSL_CERT} \
    -subj "/C=NA/ST=NA/L=NA/O=NA/OU=NA/CN=vsftpd"
bcg-done
