#!/usr/bin/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Create FTP configuration
#======================================================================================================================

[[ -z "${EXTERNAL_URI-}" ]] &&  [[ -z "${EXTERNAL_IP-}" ]] && bcg-error

bcg-echo "Writing VSFTPD config..."
esh -o /etc/vsftpd/vsftpd.conf \
    /etc/templates/vsftpd.conf.esh
bcg-done
