#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Create FTP configuration.
#======================================================================================================================

if [ -f ${FTPS_SSL_CERT} ] ; then
    bf-echo "Using existing SSL certificate."
    exit 0
fi

bf-echo "Creating SSL certificate and key..."
openssl req -newkey rsa:${FTPS_SSL_BITS} \
    -x509 \
    -sha256 \
    -days 3650 \
    -nodes \
    -out ${FTPS_SSL_CERT} \
    -keyout ${FTPS_SSL_CERT} \
    -subj "/C=NA/ST=NA/L=NA/O=NA/OU=NA/CN=vsftpd"
bf-done
