#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Create vsftp configuration.
#======================================================================================================================

if [ -z "${FTPS_USER-}" ] ; then
    bf-error "You must provide the FTPS user."
fi

if [ -z "${FTPS_EXTERNAL_URI-}" ] && [ -z "${FTPS_EXTERNAL_IP-}" ] ; then
    bf-error "You must provide either an external URI or IP."
fi

bf-echo "Writing vsftpd config..."
esh -o ${FTPS_VSFTPD_CONF} \
    ${BF_TEMPLATES}/vsftpd.conf.esh
bf-done
