#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Create lftp configuration.
#======================================================================================================================

bf-echo "Writing lftp config..."
esh -o ${FTPS_LFTP_CONF} \
    ${BF_TEMPLATES}/lftp.conf.esh
bf-done
