#!/usr/bin/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Create lftp configuration.
#======================================================================================================================

bf-echo "Writing lftp config..."
bf-esh ${BF_TEMPLATES}/lftp.conf.esh ${FTPS_LFTP_CONF}
bf-done
