#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bf-env "FTPS_FILES" "/files"

bf-env "FTPS_VSFTPD_CONF" "/etc/vsftpd/vsftpd.conf"
bf-env "FTPS_VSFTPD_LOG_FILE" "/var/log/vsftpd.log"
bf-env "FTPS_VSFTPD_CERT" "/ssl/vsftpd.pem"

bf-env "FTPS_LFTP_CONF" "/etc/lftp.conf"
