#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Create FTP user.
#======================================================================================================================

[[ -z "${FTPS_USER-}" ]] && bf-error "FTPS_USER is required."
[[ -z "${FTPS_PASS-}" ]] && bf-error "FTPS_PASS is required."

USER=${FTPS_USER}
PASS=${FTPS_PASS}
UID=${FTPS_UID:-1000}
HOME=${FTPS_FILES}

bf-echo "Creating user ${USER}..."
echo -e "${PASS}\n${PASS}" | adduser -h ${HOME} -s /sbin/nologin -u ${UID} ${USER}
bf-done

bf-echo "Ensuring user owns ${HOME}..."
chown ${USER}:${USER} ${HOME}
bf-done
