#!/usr/bin/with-contenv sh

set -euo pipefail
export BCG_E="vsftpd-log/$(basename ${0})"


#======================================================================================================================
# Forward vsftpd error log to Docker.
#======================================================================================================================

bcg-forward "vsftpd-log" "${VSFTPD_LOG}"
