name: auto-release

on:
  pull_request:
    types: [closed]

jobs:
  create-release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    -
      name: Create Release ${{ github.event.pull_request.title }}
      uses: bfren/create-release@v1
      with:
        token: ${{ secrets.PAT }}
        repo: ${{ github.repository }}
        pr_title: ${{ github.event.pull_request.title }}
